services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    environment:
      - API_URL=${API_URL:-http://localhost:3500}
    restart: always
    depends_on:
      - back
    networks:
      - dokploy-network
      - internal-network

  back:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-izzzi}?schema=public
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET:-supersecret}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-supersecretrefresh}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - CORS_ORIGIN=https://${DOMAIN_NAME}
      - PORT=3500
    depends_on:
      - db
    networks:
      - dokploy-network
      - internal-network

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-izzzi}
    restart: always
    networks:
      - internal-network

volumes:
  db_data:


networks:
  dokploy-network:
    external: true
  internal-network:
    driver: bridge
