name: CI

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            back/package-lock.json
            front/package-lock.json

      - name: Install Back dependencies
        run: npm install
        working-directory: back

      - name: Build Back
        run: npm run build
        working-directory: back

      - name: Install Front dependencies
        run: npm install
        working-directory: front

      - name: Build Front
        run: npm run build
        working-directory: front
